In [1]:
import pandas as pd

In [9]:
import os
print(os.listdir())

['.ipynb_checkpoints', 'projects.csv', 'project_data.db', 'project_data.db-journal', 'resources.csv', 'tasks.csv', 'Untitled.ipynb']

In [10]:
projects=pd.read_csv('projects.csv')
projects.head()

,Project_id,Project_Name,Department,Start_Date,End_Date,Budget,TASK_COUNT,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,PRJ001,Cloud Migration Phase 1,IT,01-01-2024,30-06-2024,"? 5,00,000.00",5,NaN,NaN,NaN
1,PRJ002,Website Redesign,Marketing,15-02-2024,15-08-2024,"? 2,00,000.00",4,NaN,NaN,NaN
2,PRJ003,Employee Onboarding Revamp,HR,01-03-2024,01-06-2024,"? 75,000.00",3,NaN,NaN,NaN
3,PRJ004,Mobile App Development,IT,01-04-2024,01-11-2024,"? 3,50,000.00",4,NaN,NaN,NaN
4,PRJ005,Office Relocation,Operations,01-05-2024,01-08-2024,"? 1,20,000.00",3,NaN,NaN,NaN

In [11]:
tasks=pd.read_csv('tasks.csv')
resources=pd.read_csv('resources.csv')

In [12]:
tasks.head()

,Task_ID,Project_ID,Task_Name,Department,Assigned_Role,Planned_Hours,Actual_Hours,Status
0,TSK001,PRJ001,Requirement Gathering,IT,Business Analyst,40,38,Completed
1,TSK002,PRJ001,Architecture Design,IT,Solution Architect,60,65,Completed
2,TSK003,PRJ001,Cloud Readiness Assessment,IT,Cloud Engineer,30,28,Completed
3,TSK004,PRJ001,Data Migration Script,IT,Data Engineer,80,90,In Progress
4,TSK005,PRJ001,User Acceptance Testing,IT,QA Tester,40,45,Not Started

In [13]:
resources.head()

,Resource_ID,Name,Role,Department,Hourly_Rate,Availability
0,RES001,John Smith,Business Analyst,IT,85,100%
1,RES002,Sarah Jones,Solution Architect,IT,110,80%
2,RES003,Mike Brown,Cloud Engineer,IT,95,100%
3,RES004,Emily Davis,Data Engineer,IT,90,90%
4,RES005,David Wilson,QA Tester,IT,65,100%

In [25]:
projects.rename(columns={'Project_id': 'Project_ID'}, inplace=True)
print(projects.columns)

Index(['Project_ID', 'Project_Name', 'Department', 'Start_Date', 'End_Date',
       'Budget', 'TASK_COUNT', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9'],
      dtype='object')

In [28]:
tasks_with_projects=tasks.merge(projects,on='Project_ID',how='left')
tasks_with_projects.head()

,Task_ID,Project_ID,Task_Name,Department_x,Assigned_Role,Planned_Hours,Actual_Hours,Status,Project_Name,Department_y,Start_Date,End_Date,Budget,TASK_COUNT,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,TSK001,PRJ001,Requirement Gathering,IT,Business Analyst,40,38,Completed,Cloud Migration Phase 1,IT,01-01-2024,30-06-2024,"? 5,00,000.00",5,NaN,NaN,NaN
1,TSK002,PRJ001,Architecture Design,IT,Solution Architect,60,65,Completed,Cloud Migration Phase 1,IT,01-01-2024,30-06-2024,"? 5,00,000.00",5,NaN,NaN,NaN
2,TSK003,PRJ001,Cloud Readiness Assessment,IT,Cloud Engineer,30,28,Completed,Cloud Migration Phase 1,IT,01-01-2024,30-06-2024,"? 5,00,000.00",5,NaN,NaN,NaN
3,TSK004,PRJ001,Data Migration Script,IT,Data Engineer,80,90,In Progress,Cloud Migration Phase 1,IT,01-01-2024,30-06-2024,"? 5,00,000.00",5,NaN,NaN,NaN
4,TSK005,PRJ001,User Acceptance Testing,IT,QA Tester,40,45,Not Started,Cloud Migration Phase 1,IT,01-01-2024,30-06-2024,"? 5,00,000.00",5,NaN,NaN,NaN

In [29]:
resources.rename(columns={'Role': 'Assigned_Role'}, inplace=True)

In [30]:
full_data = tasks_with_projects.merge(resources, on='Assigned_Role', how='left')
full_data.head()

,Task_ID,Project_ID,Task_Name,Department_x,Assigned_Role,Planned_Hours,Actual_Hours,Status,Project_Name,Department_y,...,Budget,TASK_COUNT,Unnamed: 7,Unnamed: 8,Unnamed: 9,Resource_ID,Name,Department,Hourly_Rate,Availability
0,TSK001,PRJ001,Requirement Gathering,IT,Business Analyst,40,38,Completed,Cloud Migration Phase 1,IT,...,"? 5,00,000.00",5,NaN,NaN,NaN,RES001,John Smith,IT,85.0,100%
1,TSK002,PRJ001,Architecture Design,IT,Solution Architect,60,65,Completed,Cloud Migration Phase 1,IT,...,"? 5,00,000.00",5,NaN,NaN,NaN,RES002,Sarah Jones,IT,110.0,80%
2,TSK003,PRJ001,Cloud Readiness Assessment,IT,Cloud Engineer,30,28,Completed,Cloud Migration Phase 1,IT,...,"? 5,00,000.00",5,NaN,NaN,NaN,RES003,Mike Brown,IT,95.0,100%
3,TSK004,PRJ001,Data Migration Script,IT,Data Engineer,80,90,In Progress,Cloud Migration Phase 1,IT,...,"? 5,00,000.00",5,NaN,NaN,NaN,RES004,Emily Davis,IT,90.0,90%
4,TSK005,PRJ001,User Acceptance Testing,IT,QA Tester,40,45,Not Started,Cloud Migration Phase 1,IT,...,"? 5,00,000.00",5,NaN,NaN,NaN,RES005,David Wilson,IT,65.0,100%

In [31]:
from sklearn.linear_model import LinearRegression

In [32]:
X = full_data[['Planned_Hours', 'Hourly_Rate']].dropna()
y = full_data.loc[X.index, 'Actual_Hours']

In [33]:
model = LinearRegression()
model.fit(X, y)

LinearRegression()

In [35]:

prediction = model.predict([[40, 85]])
print(f"Predicted Actual Hours: {prediction[0]:.1f}")

Predicted Actual Hours: 42.2

C:\Users\Asus\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [36]:
task_summary = full_data.groupby('Project_ID').agg(
    Total_Planned_Hours=('Planned_Hours', 'sum'),
    Total_Actual_Hours=('Actual_Hours', 'sum'),
    Task_Count=('Task_ID', 'count')
).reset_index()

In [37]:
task_summary.head()

  Project_ID  Total_Planned_Hours  Total_Actual_Hours  Task_Count
0     PRJ001                  250                 266           5
1     PRJ002                  250                 263           4
2     PRJ003                   55                  55           3
3     PRJ004                  270                 300           4
4     PRJ005                   95                 104           3

In [38]:
# Merge the task summary with the projects table (keep only projects that have tasks)
project_data = task_summary.merge(projects, on='Project_ID', how='inner')
project_data.head()

,Project_ID,Total_Planned_Hours,Total_Actual_Hours,Task_Count,Project_Name,Department,Start_Date,End_Date,Budget,TASK_COUNT,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,PRJ001,250,266,5,Cloud Migration Phase 1,IT,01-01-2024,30-06-2024,"? 5,00,000.00",5,NaN,NaN,NaN
1,PRJ002,250,263,4,Website Redesign,Marketing,15-02-2024,15-08-2024,"? 2,00,000.00",4,NaN,NaN,NaN
2,PRJ003,55,55,3,Employee Onboarding Revamp,HR,01-03-2024,01-06-2024,"? 75,000.00",3,NaN,NaN,NaN
3,PRJ004,270,300,4,Mobile App Development,IT,01-04-2024,01-11-2024,"? 3,50,000.00",4,NaN,NaN,NaN
4,PRJ005,95,104,3,Office Relocation,Operations,01-05-2024,01-08-2024,"? 1,20,000.00",3,NaN,NaN,NaN

In [40]:
project_data['Delayed'] = (project_data['Total_Actual_Hours'] > project_data['Total_Planned_Hours']).astype(int)

In [41]:

project_data['Delayed'].value_counts()

Delayed
1    17
0     9
Name: count, dtype: int64

In [42]:
# Select features (X) and target (y)
features = ['Task_Count', 'Budget', 'Department']
X = project_data[features].copy()
y = project_data['Delayed']

In [43]:
# One-hot encode the 'Department' column
X_encoded = pd.get_dummies(X, columns=['Department'], drop_first=True)

In [44]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [48]:
# Remove everything except digits and decimal point, then convert to float
project_data['Budget'] = project_data['Budget'].str.replace(r'[^\d.]', '', regex=True).astype(float)

In [49]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# Summarise tasks per project
task_summary = full_data.groupby('Project_ID').agg(
    Total_Planned_Hours=('Planned_Hours', 'sum'),
    Total_Actual_Hours=('Actual_Hours', 'sum'),
    Task_Count=('Task_ID', 'count')
).reset_index()

# Merge with projects table
project_data = task_summary.merge(projects, on='Project_ID', how='inner')

# --- Clean Budget: keep only digits and decimal point ---
project_data['Budget'] = project_data['Budget'].str.replace(r'[^\d.]', '', regex=True).astype(float)

# Create 'Delayed' column (1 = delayed, 0 = on time)
project_data['Delayed'] = (
    project_data['Total_Actual_Hours'] > project_data['Total_Planned_Hours']
).astype(int)

# Features and target
features = ['Task_Count', 'Budget', 'Department']
X = project_data[features].copy()
y = project_data['Delayed']

# One-hot encode Department
X_encoded = pd.get_dummies(X, columns=['Department'], drop_first=True)

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, test_size=0.2, random_state=42
)

# Train model
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Predict and evaluate
y_pred = model.predict(X_test)
accuracy = (y_pred == y_test).mean()
print(f"Model Accuracy: {accuracy:.2f}")

Model Accuracy: 0.50

In [ ]:
# ---- Interactive Delay Predictor ----
print("🔮 Project Delay Predictor")
print("Enter the details of a new project to see if it's likely to be delayed.\n")

# Get user input
task_count = int(input("Number of tasks: "))
budget = float(input("Budget (in dollars, e.g. 200000): "))
department = input("Department (e.g. IT, Marketing, HR, Operations, Sales): ").strip()

# Create a one-row dataframe
new_project = pd.DataFrame({
    'Task_Count': [task_count],
    'Budget': [budget],
    'Department': [department]
})

# One-hot encode, aligning with training columns
new_encoded = pd.get_dummies(new_project, columns=['Department'], drop_first=True)
for col in X_encoded.columns:
    if col not in new_encoded.columns:
        new_encoded[col] = 0
new_encoded = new_encoded[X_encoded.columns]

# Predict
prediction = model.predict(new_encoded)[0]
probability = model.predict_proba(new_encoded)[0][1]  # probability of being delayed

# Output result
print("\n--- Prediction ---")
if prediction == 1:
    print(f"⚠️  This project is likely to be DELAYED (probability: {probability:.0%})")
else:
    print(f"✅  This project is likely to be ON TIME (probability of delay: {probability:.0%})")

🔮 Project Delay Predictor
Enter the details of a new project to see if it's likely to be delayed.